services:
  - type: web
    name: hsv-stages
    runtime: docker
    plan: free
    dockerfilePath: ./deploy/Dockerfile
    dockerContext: .
    healthCheckPath: /up
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_PORT
        value: 5432
      - key: DB_HOST
        sync: false
      - key: DB_DATABASE
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: APP_KEY
        sync: false
      - key: APP_URL
        sync: false
      - key: MAIL_MAILER
        sync: false
      - key: MAIL_HOST
        sync: false
      - key: MAIL_PORT
        sync: false
      - key: MAIL_USERNAME
        sync: false
      - key: MAIL_PASSWORD
        sync: false
      - key: MAIL_ENCRYPTION
        sync: false
      - key: MAIL_FROM_ADDRESS
        sync: false
      - key: WHATSAPP_NUMBER
        sync: false
      - key: ORANGE_MONEY_NUMBER
        sync: false
      - key: MTN_MOMO_NUMBER
        sync: false
